// Package brand embeds the sleeping sloth (variant c2) so the app can show it in its resting
// states. The files are generated by generate.py in this folder.
package brand

import _ "embed"

// SleepingSVG is the 32x32 pixel grid of the logo: the sleeping frame of the mascot is exactly this.
//
//go:embed reposo/lazymark.svg
var SleepingSVG string

// Sprite36 holds the resting mascot for Kitty: 36x36 frames (the 32x32 logo on a canvas with room to hop and
// stretch), the frames of its animations and their sequences. The app scales it by an integer factor.
// Generated by mascot.py.
//
//go:embed reposo/sprite36.txt
var Sprite36 string

// Sprite8 holds the same animations for quadrant blocks: 16x8 pixels (2x2 per cell, 8x4 cells). Generated by
// mascot.py.
//
//go:embed reposo/sprite8.txt
var Sprite8 string
