// Package brand embeds the sleeping sloth (variant c2) so the app can show it in its resting
// states. The files are generated by generate.py in this folder.
package brand

import _ "embed"

// SleepingPNG is the 128 px export, used with the Kitty graphics protocol.
//
//go:embed reposo/lazymark-128.png
var SleepingPNG []byte

// SleepingSVG is the 32x32 pixel grid, used for the half-block fallback.
//
//go:embed reposo/lazymark.svg
var SleepingSVG string

// Sprite16 holds the resting mascot at 16x16 (the logo is too detailed to read at the small size the app
// draws it): the sleeping frame, the frames of its click animations and the animation sequences. Generated
// by sprite16.py.
//
//go:embed reposo/sprite16.txt
var Sprite16 string

// Sprite32 holds the same frames and animations at 32x32, made from the layers of the logo (the sleeping
// frame is the logo itself). The app shows these with Kitty, scaled by an integer factor; Sprite16 is
// for half blocks. Generated by sprite32.py.
//
//go:embed reposo/sprite32.txt
var Sprite32 string
