// Package brand embeds the resting mascot (the sleeping sloth, variant c2, and its animations) so the app can show
// it in its resting states. The files are generated by generate.py and mascot.py in this folder.
package brand

import _ "embed"

// Sprite36 holds the resting mascot for Kitty: 36x36 frames (the 32x32 logo on a canvas with room to hop and
// stretch), the frames of its animations and their sequences. The app scales it by an integer factor.
// Generated by mascot.py.
//
//go:embed reposo/sprite36.txt
var Sprite36 string

// Sprite8 holds the same animations for quadrant blocks: 16x8 pixels (2x2 per cell, 8x4 cells). Generated by
// mascot.py.
//
//go:embed reposo/sprite8.txt
var Sprite8 string
