#!/usr/bin/env python3
"""Generates the frames of the resting mascot at 32x32, from the layers of the logo (generate.py).

The sleeping frame is exactly the composite of reposo/ (the approved logo, variant c2). The animation
frames come from the same layers: the eyes open (the c1 eyes on the c2 body), the arm lifts the pencil, the
sloth steps from side to side, and it turns around. Run it from anywhere:

    python3 assets/brand/sprite32.py

It writes reposo/sprite32.txt (embedded in the binary, same format as sprite16.txt, with the same frame
and animation names) and reposo/hoja-animaciones-32.svg/.png, a contact sheet for review.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import generate as g  # noqa: E402
from sprite16 import ANIMS  # noqa: E402

OUT = os.path.join(HERE, "reposo")
N = 32


def composite(variant, arm_dy=0, pencil_dy=None):
    """The three layers, base then pencil then claws, as {(x, y): '#rrggbb'}."""
    if pencil_dy is None:
        pencil_dy = arm_dy
    x0, y0, n = g.PENCIL
    out = {}
    for layer in (g.sloth_base(variant, arm_dy), g.pencil(x0, y0 + pencil_dy, n), g.claws(pencil_dy)):
        out.update(layer)
    return out


def shift(c, dx, dy=0):
    return {(x + dx, y + dy): v for (x, y), v in c.items() if 0 <= x + dx < N and 0 <= y + dy < N}


def squash(c, width):
    """Horizontal squash around the middle of the sprite: keeps `width` of the 32 columns, nearest neighbor."""
    out = {}
    off = (N - width) // 2
    for x in range(width):
        sx = x * N // width
        for y in range(N):
            if (sx, y) in c:
                out[(x + off, y)] = c[(sx, y)]
    return out


def back(c):
    """Seen from behind: the face and the belly become fur. Only the interior pixels of the head and the
    belly change; the outline stays."""
    fur = g.PALETTES["c2"]["fur"]
    out = dict(c)
    face = {g.PALETTES["c2"]["face"], g.PALETTES["c2"]["patch"], g.CHEEK, g.PALETTES["c2"]["belly"]}
    for (x, y), v in c.items():
        interior = all((x + dx, y + dy) in c for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
        if v in face and y < 27 and x < 21:
            out[(x, y)] = fur
        elif v == g.CRUST and interior and y < 17 and x < 21:  # eyes and nose
            out[(x, y)] = fur
    return out


def frames():
    f = {}
    sleep = composite("c2")
    awake = composite("c2w")
    f["sleep"] = sleep
    f["blink"] = sleep
    f["awake"] = awake
    f["awake2"] = shift(awake, 0, 0)
    # the glint of the open eyes: a light pixel in each eye
    glint = dict(awake)
    for x in (7, 17):
        glint[(x, 9)] = "#fdf1cf"
    f["awake"] = glint
    # wave: the arm lifts the pencil and wags it
    f["wave1"] = composite("c2w", -3)
    f["wave2"] = composite("c2w", -5)
    # dance: the whole sloth steps from side to side
    f["dance1"] = shift(awake, -2)
    f["dance2"] = shift(awake, 2, -1)
    f["dance3"] = shift(awake, 0, -2)
    # spin: squashes, turns its back and squashes again
    f["spin1"] = squash(awake, 24)
    f["spin2"] = squash(back(awake), 14)
    f["spin3"] = back(awake)
    f["spin4"] = squash(back(awake), 14)
    f["spin5"] = squash(awake, 24)
    return f


def write_txt(f):
    colors = sorted({v for c in f.values() for v in c.values()})
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    pal = {col: letters[i] for i, col in enumerate(colors)}
    lines = ["# Resting mascot: 32x32 frames. Generated by sprite32.py from the layers of the logo; do not edit.",
             "# palette: letter = hex color"]
    lines += [f"{pal[col]} {col.lstrip('#')}" for col in colors]
    for name, c in f.items():
        lines.append(f"@frame {name}")
        for y in range(N):
            lines.append("".join(pal.get(c.get((x, y)), ".") for x in range(N)))
    for name, seq in ANIMS:
        lines.append(f"@anim {name} {' '.join(seq)}")
    open(os.path.join(OUT, "sprite32.txt"), "w").write("\n".join(lines) + "\n")


def write_sheet(f):
    scale, pad = 4, 10
    cell = N * scale + pad
    maxlen = max(len(s) for _, s in ANIMS)
    w, h = (maxlen + 1) * cell + pad, (len(ANIMS) + 1) * (cell + 18) + pad
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" shape-rendering="crispEdges">',
           f'<rect width="{w}" height="{h}" fill="#1e1e2e"/>']

    def draw(c, ox, oy, label):
        for (x, y), v in sorted(c.items(), key=lambda t: (t[0][1], t[0][0])):
            out.append(f'<rect x="{ox + x * scale}" y="{oy + y * scale}" width="{scale}" height="{scale}" fill="{v}"/>')
        out.append(f'<text x="{ox}" y="{oy + N * scale + 13}" font-family="monospace" font-size="11" fill="#a6adc8">{label}</text>')

    draw(f["sleep"], pad, pad, "sleep (resting = the logo)")
    for r, (name, seq) in enumerate(ANIMS):
        oy = pad + (r + 1) * (cell + 18)
        out.append(f'<text x="{pad}" y="{oy - 4}" font-family="monospace" font-size="13" fill="#cba6f7">{name}</text>')
        for i, fr in enumerate(seq):
            draw(f[fr], pad + i * cell, oy, f"{i + 1}: {fr}")
    out.append("</svg>")
    open(os.path.join(OUT, "hoja-animaciones-32.svg"), "w").write("\n".join(out))


if __name__ == "__main__":
    f = frames()
    write_txt(f)
    write_sheet(f)
    print("ok", len(f), "frames")
