#!/usr/bin/env python3
"""Generates the resting mascot for the app: a 16x16 sleeping sloth and its click animations.

At the small size the app draws it (16 columns x 8 rows of half blocks, or the same grid scaled by an
integer factor with Kitty), the 32x32 logo is not legible, so this is a hand-drawn 16x16 version of the
same sloth (variant c2: earth tones, sleeping, a pencil in its hand). Run it from anywhere:

    python3 assets/brand/sprite16.py

It writes reposo/sprite16.txt (embedded in the binary) and reposo/hoja-animaciones.svg/.png (a contact
sheet of every frame, for review).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "reposo")

PALETTE = {
    "K": "11111b",  # outline
    "F": "c99a6e",  # fur
    "A": "b5855c",  # arm
    "C": "f3e2c7",  # cream face and belly
    "P": "7a4f3a",  # eye patch
    "N": "f5c2e7",  # cheek
    "T": "fdf1cf",  # eye glint
    "G": "6c7086",  # graphite
    "W": "e3c59b",  # wood
    "Y": "f9e2af",  # pencil body
    "S": "fab387",  # pencil shade
    "L": "a6adc8",  # ferrule
    "R": "f5c2e7",  # eraser
}

SLEEP = [
    "................",
    "..KKKKKK........",
    ".KFFFFFFK.......",
    "KFFFFFFFFK......",
    "KFCCCCCCFK......",
    "KPPCCCCPPK......",
    "KKKCCCCKKK......",  # closed eyes: a dark line in each patch
    "KFCCKKCCFK......",
    "KNCCCCCCNK......",
    ".KFFCCFFK.......",
    "KKFFFFFFKK......",
    "KAKFCCFFKGWYYYLR",
    "KAKFCCFFKWWSSSLR",
    "KAKFCCFFK.......",
    ".KKFFFFFK.......",
    "..KKKKKKK.......",
]


def grid(rows):
    return [list(r) for r in rows]


def rows(g):
    return ["".join(r) for r in g]


def set_px(g, x, y, c):
    if 0 <= y < 16 and 0 <= x < 16:
        g[y][x] = c


def awake(g, glint=True):
    """Open eyes: a dark pixel in each patch, with a light glint above it."""
    g[6][1:3] = ["P", "K"]
    g[6][7:10] = ["K", "P", "K"]
    if glint:
        set_px(g, 2, 5, "T")
        set_px(g, 7, 5, "T")
    return g


def shift(g, dx, dy=0):
    out = [["."] * 16 for _ in range(16)]
    for y in range(16):
        for x in range(16):
            if g[y][x] != "." and 0 <= x + dx < 16 and 0 <= y + dy < 16:
                out[y + dy][x + dx] = g[y][x]
    return out


def move_pencil(g, dy):
    """Moves the pencil and the hand around it (columns 8 to 15, rows 11 and 12) up or down."""
    out = [r[:] for r in g]
    for y in (11, 12):
        for x in range(8, 16):
            out[y][x] = "."
    for y in (11, 12):
        for x in range(8, 16):
            if 0 <= y + dy < 16:
                out[y + dy][x] = g[y][x]
    return out


def back(g):
    """Seen from behind: no face, just fur."""
    out = [r[:] for r in g]
    for y in range(3, 10):
        for x in range(16):
            if out[y][x] in "CPNTK" and 1 <= x <= 8 and 4 <= y <= 8 and not (out[y][x] == "K" and x in (0, 9)):
                out[y][x] = "F"
    for y in range(11, 14):
        for x in range(3, 8):
            if out[y][x] == "C":
                out[y][x] = "F"
    return out


def squash(g, keep):
    """Turning: keeps only some of the columns 0 to 9 (the body), re-centered; the pencil stays."""
    out = [["."] * 16 for _ in range(16)]
    cols = keep
    off = (10 - len(cols)) // 2
    for y in range(16):
        for i, x in enumerate(cols):
            out[y][off + i] = g[y][x]
        for x in range(10, 16):
            out[y][x] = g[y][x]
    return out


def frames():
    f = {}
    f["sleep"] = grid(SLEEP)
    f["awake"] = awake(grid(SLEEP))
    f["awake2"] = awake(grid(SLEEP), glint=False)
    f["blink"] = grid(SLEEP)
    # wave: the hand lifts the pencil and wags it
    up1 = move_pencil(awake(grid(SLEEP)), -2)
    up2 = move_pencil(awake(grid(SLEEP)), -3)
    f["wave1"], f["wave2"] = up1, up2
    # dance: the whole sloth steps from side to side
    f["dance1"] = shift(awake(grid(SLEEP)), -1)
    f["dance2"] = shift(awake(grid(SLEEP)), 1, -1)
    f["dance3"] = shift(awake(grid(SLEEP)), 0, -1)
    # spin: squashes, turns its back, squashes again
    base = awake(grid(SLEEP))
    f["spin1"] = squash(base, [0, 1, 2, 3, 5, 6, 8, 9])
    f["spin2"] = squash(back(base), [0, 1, 3, 5, 6, 9])
    f["spin3"] = back(base)
    f["spin4"] = squash(back(base), [0, 1, 3, 5, 6, 9])
    f["spin5"] = squash(base, [0, 1, 2, 3, 5, 6, 8, 9])
    return f


ANIMS = [
    ("wake", ["awake", "awake", "awake2", "awake", "awake", "awake2", "awake", "awake"]),
    ("wave", ["awake", "wave1", "wave2", "wave1", "wave2", "wave1", "wave2", "awake"]),
    ("dance", ["dance1", "dance2", "dance1", "dance3", "dance2", "dance1", "dance3", "dance1", "dance2", "awake"]),
    ("spin", ["awake", "spin1", "spin2", "spin3", "spin4", "spin5", "awake", "awake"]),
]


def write_txt(f):
    lines = ["# Resting mascot: 16x16 frames. Generated by sprite16.py; do not edit.", "# palette: letter = hex color"]
    for k, v in PALETTE.items():
        lines.append(f"{k} {v}")
    for name, g in f.items():
        lines.append(f"@frame {name}")
        lines.extend(rows(g))
    for name, seq in ANIMS:
        lines.append(f"@anim {name} {' '.join(seq)}")
    open(os.path.join(OUT, "sprite16.txt"), "w").write("\n".join(lines) + "\n")


def write_sheet(f):
    scale, pad = 10, 14
    cell = 16 * scale + pad
    maxlen = max(len(s) for _, s in ANIMS)
    w, h = (maxlen + 1) * cell + pad, (len(ANIMS) + 1) * (cell + 18) + pad
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" shape-rendering="crispEdges">',
           f'<rect width="{w}" height="{h}" fill="#1e1e2e"/>']

    def draw(g, ox, oy, label):
        for y in range(16):
            for x in range(16):
                c = g[y][x]
                if c != ".":
                    out.append(f'<rect x="{ox + x * scale}" y="{oy + y * scale}" width="{scale}" height="{scale}" fill="#{PALETTE[c]}"/>')
        out.append(f'<text x="{ox}" y="{oy + 16 * scale + 13}" font-family="monospace" font-size="11" fill="#a6adc8">{label}</text>')

    draw(f["sleep"], pad, pad, "sleep (resting)")
    for r, (name, seq) in enumerate(ANIMS):
        oy = pad + (r + 1) * (cell + 18)
        out.append(f'<text x="{pad}" y="{oy - 4}" font-family="monospace" font-size="13" fill="#cba6f7">{name}</text>')
        for i, fr in enumerate(seq):
            draw(f[fr], pad + i * cell, oy, f"{i + 1}: {fr}")
    out.append("</svg>")
    open(os.path.join(OUT, "hoja-animaciones.svg"), "w").write("\n".join(out))


if __name__ == "__main__":
    f = frames()
    write_txt(f)
    write_sheet(f)
    print("ok", len(f), "frames")
