// Package sprite draws a pixel-art SVG (one <rect> per pixel on a square grid, like the files
// generated by assets/brand/generate.py) and draws pixel frames: as quadrant-block text (each cell shows 2x2
// pixels, in exact truecolor) or as an integer-scaled image for the Kitty graphics protocol.
package sprite

import (
	"fmt"
	"image"
	"image/color"
	"regexp"
	"strconv"
	"strings"
)

// Pixel is an RGB color; Set is false for a transparent pixel.
type Pixel struct {
	R, G, B uint8
	Set     bool
}

// Grid is a pixel grid indexed [y][x].
type Grid [][]Pixel

var (
	rectRe    = regexp.MustCompile(`<rect\s+x="(\d+)"\s+y="(\d+)"\s+width="1"\s+height="1"\s+fill="#([0-9a-fA-F]{6})"\s*/>`)
	viewBoxRe = regexp.MustCompile(`viewBox="0 0 (\d+) (\d+)"`)
)

// ParseSVG reads the pixel grid of svg. Later rects paint over earlier ones, as in the SVG.
func ParseSVG(svg string) (Grid, error) {
	m := viewBoxRe.FindStringSubmatch(svg)
	if m == nil {
		return nil, fmt.Errorf("sprite: the SVG has no viewBox")
	}
	w, _ := strconv.Atoi(m[1])
	h, _ := strconv.Atoi(m[2])
	g := make(Grid, h)
	for y := range g {
		g[y] = make([]Pixel, w)
	}
	for _, r := range rectRe.FindAllStringSubmatch(svg, -1) {
		x, _ := strconv.Atoi(r[1])
		y, _ := strconv.Atoi(r[2])
		if x >= w || y >= h {
			continue
		}
		v, _ := strconv.ParseUint(r[3], 16, 32)
		g[y][x] = Pixel{uint8(v >> 16), uint8(v >> 8), uint8(v), true}
	}
	return g, nil
}

// Size is the grid width and height in pixels.
func (g Grid) Size() (w, h int) {
	if len(g) == 0 {
		return 0, 0
	}
	return len(g[0]), len(g)
}

func fg(p Pixel) string { return fmt.Sprintf("\x1b[38;2;%d;%d;%dm", p.R, p.G, p.B) }
func bg(p Pixel) string { return fmt.Sprintf("\x1b[48;2;%d;%d;%dm", p.R, p.G, p.B) }

// quadrant is the block character for a 2x2 pixel mask: bit 0 upper left, 1 upper right, 2 lower left, 3 lower right.
var quadrant = [16]string{" ", "▘", "▝", "▀", "▖", "▌", "▞", "▛", "▗", "▚", "▐", "▜", "▄", "▙", "▟", "█"}

// QuadrantCells draws g (whose size is even) as cells of 2x2 pixels, each a quadrant block with at most two
// colors in exact truecolor: cells[row][column] is the text of one cell. A cell with a transparent pixel keeps the
// screen's background there (and shows its opaque pixels in their average color); a fully opaque cell picks the
// split of its four pixels into two colors that loses the least.
func QuadrantCells(g Grid) [][]string {
	w, h := g.Size()
	rows := make([][]string, 0, h/2)
	for y := 0; y+1 < h; y += 2 {
		row := make([]string, 0, w/2)
		for x := 0; x+1 < w; x += 2 {
			px := [4]Pixel{g[y][x], g[y][x+1], g[y+1][x], g[y+1][x+1]}
			row = append(row, quadrantCell(px))
		}
		rows = append(rows, row)
	}
	return rows
}

func avg(px [4]Pixel, mask int) (Pixel, int) {
	var r, g, b, n int
	for i := 0; i < 4; i++ {
		if mask>>i&1 == 1 && px[i].Set {
			r, g, b, n = r+int(px[i].R), g+int(px[i].G), b+int(px[i].B), n+1
		}
	}
	if n == 0 {
		return Pixel{}, 0
	}
	return Pixel{uint8(r / n), uint8(g / n), uint8(b / n), true}, n
}

func dist(a, b Pixel) int {
	dr, dg, db := int(a.R)-int(b.R), int(a.G)-int(b.G), int(a.B)-int(b.B)
	return dr*dr + dg*dg + db*db
}

func quadrantCell(px [4]Pixel) string {
	opaque := 0
	for i, p := range px {
		if p.Set {
			opaque |= 1 << i
		}
	}
	switch opaque {
	case 0:
		return " "
	case 15:
	default: // some transparent: the opaque pixels, in their average color, over the screen's background
		c, _ := avg(px, opaque)
		return fg(c) + quadrant[opaque] + "\x1b[m"
	}
	best, bestErr := 0, -1
	for mask := 1; mask < 15; mask++ { // the pixels in mask are the foreground, the rest the background
		f, _ := avg(px, mask)
		b, _ := avg(px, 15&^mask)
		e := 0
		for i, p := range px {
			if mask>>i&1 == 1 {
				e += dist(p, f)
			} else {
				e += dist(p, b)
			}
		}
		if bestErr < 0 || e < bestErr {
			best, bestErr = mask, e
		}
	}
	f, _ := avg(px, best)
	b, _ := avg(px, 15&^best)
	if dist(f, b) == 0 { // one color
		return fg(f) + "█\x1b[m"
	}
	return fg(f) + bg(b) + quadrant[best] + "\x1b[m"
}

// Quadrants is QuadrantCells with each row joined into a line.
func Quadrants(g Grid) []string {
	cells := QuadrantCells(g)
	lines := make([]string, len(cells))
	for i, row := range cells {
		lines[i] = strings.Join(row, "")
	}
	return lines
}

// Anim is a named sequence of frames.
type Anim struct {
	Name   string
	Frames []string
}

// Frames is a set of named pixel grids and the animations made of them.
type Frames struct {
	Grids map[string]Grid
	Anims []Anim
}

// ParseFrames reads the text format written by assets/brand/mascot.py: palette lines ("K 11111b"),
// "@frame name" followed by rows of palette letters ('.' is transparent) and "@anim name f1 f2 …".
func ParseFrames(text string) (*Frames, error) {
	pal := map[byte]Pixel{}
	out := &Frames{Grids: map[string]Grid{}}
	var cur string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimRight(line, "\r")
		switch {
		case line == "" || strings.HasPrefix(line, "#"):
		case strings.HasPrefix(line, "@frame "):
			cur = strings.TrimSpace(strings.TrimPrefix(line, "@frame "))
			out.Grids[cur] = nil
		case strings.HasPrefix(line, "@anim "):
			f := strings.Fields(strings.TrimPrefix(line, "@anim "))
			if len(f) < 2 {
				return nil, fmt.Errorf("sprite: bad animation line %q", line)
			}
			out.Anims = append(out.Anims, Anim{Name: f[0], Frames: f[1:]})
			cur = ""
		case cur == "":
			f := strings.Fields(line)
			if len(f) != 2 || len(f[0]) != 1 || len(f[1]) != 6 {
				return nil, fmt.Errorf("sprite: bad palette line %q", line)
			}
			v, err := strconv.ParseUint(f[1], 16, 32)
			if err != nil {
				return nil, err
			}
			pal[f[0][0]] = Pixel{uint8(v >> 16), uint8(v >> 8), uint8(v), true}
		default:
			row := make([]Pixel, len(line))
			for i := 0; i < len(line); i++ {
				if line[i] != '.' {
					p, ok := pal[line[i]]
					if !ok {
						return nil, fmt.Errorf("sprite: letter %q is not in the palette (frame %s)", line[i], cur)
					}
					row[i] = p
				}
			}
			out.Grids[cur] = append(out.Grids[cur], row)
		}
	}
	var w0, h0 int
	for name, g := range out.Grids {
		w, h := g.Size()
		if w == 0 || h == 0 {
			return nil, fmt.Errorf("sprite: frame %s is empty", name)
		}
		for _, row := range g {
			if len(row) != w {
				return nil, fmt.Errorf("sprite: frame %s has rows of different widths", name)
			}
		}
		if w0 == 0 {
			w0, h0 = w, h
		} else if w != w0 || h != h0 {
			return nil, fmt.Errorf("sprite: frame %s is %dx%d, the others %dx%d", name, w, h, w0, h0)
		}
	}
	for _, a := range out.Anims {
		for _, f := range a.Frames {
			if _, ok := out.Grids[f]; !ok {
				return nil, fmt.Errorf("sprite: animation %s uses the unknown frame %s", a.Name, f)
			}
		}
	}
	return out, nil
}

// Image scales g by an integer factor (nearest neighbor, so every pixel stays a sharp square) and
// puts it on a transparent canvas of w x h pixels, centered sideways and resting on the bottom edge (the feet).
// The factor is the largest that fits.
func (g Grid) Image(w, h int) (*image.NRGBA, int) {
	gw, gh := g.Size()
	k := max(1, min(w/gw, h/gh))
	img := image.NewNRGBA(image.Rect(0, 0, max(w, gw*k), max(h, gh*k)))
	ox, oy := (img.Bounds().Dx()-gw*k)/2, img.Bounds().Dy()-gh*k
	for y := 0; y < gh; y++ {
		for x := 0; x < gw; x++ {
			p := g[y][x]
			if !p.Set {
				continue
			}
			for j := 0; j < k; j++ {
				for i := 0; i < k; i++ {
					img.SetNRGBA(ox+x*k+i, oy+y*k+j, color.NRGBA{p.R, p.G, p.B, 255})
				}
			}
		}
	}
	return img, k
}
